### ISSUE TITLE
Android can use？

### ISSUE THREAD

**Issue by mvpdream** [hufeng/rn-china-region-picker#1]

**Comment by hufeng** [comment]
Sorry, PickerIOS was only support iOS.

I need some time to resolve android.

**Comment by mvpdream** [comment]
安卓的我弄好了~~~~

**Comment by hufeng** [comment]
赞！可以让我学习下嘛？ 或者给我一个pull-request @mvpdream

**Comment by mvpdream** [comment]
只需要把带着ios的那些组件 换成安卓里使用的组件就可以了~~~~
